server:
  port: 8080                                                                                                                                                                                                                                                                        
  servlet:
    context-path: /

# 5.7 com.mysql.jdbc.Driver
# 5.7 jdbc:mysql://localhost:3306/cos   
# jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lifefrom
    password: 1234
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true    
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      
  security:
    user:
      name: test
      password: 1234
      
  pid:
    file: C:\Spring\insta\src\main\resources\upload


